# Site settings
title: Kedar Joshi
email: kedarjoshi2308@gmail.com
description: "My personal website :)"
baseurl: "kedarjoshi"
url: ""
title_description: "My personal website :)"
title_image: "https://media-exp1.licdn.com/dms/image/C4E03AQH1Hn-bXxYZHA/profile-displayphoto-shrink_800_800/0/1603729302677?e=1627516800&v=beta&t=S5bJwaBsKp617Isl2vbW0RXJ0nBoNJnvfquXohvmHhU"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/kedar2308/kedarjoshi
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
#twitter_username: _jacobtomlinson
github_username:  kedar2308
instagram_username: joshikedar1
linkedin_link: www.linkedin.com/in/kedar-profile
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
facebook_link:

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Kedar Joshi</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
